List<String> keywords = [
  "hi",
  "hello",
  "hey",
  "good morning",
  "good afternoon",
  "job",
  "job search",
  "looking for job",
  "any openings",
  "find job",
  "resume",
  "cv",
  "curriculum vitae",
  "write resume",
  "resume tips",
  "interview",
  "prepare for interview",
  "interview tips",
  "questions in interview",
  "salary",
  "expected salary",
  "negotiate salary",
  "career path",
  "promotion",
  "growth",
  "remote",
  "work from home",
  "online job",
  "location",
  "where is the job",
  "work location",
  "apply",
  "how to apply",
  "job title",
  "company",
  "work hours",
  "benefits",
  "contract",
  "freelance",
  "full time",
  "part time",
  "job application",
  "cv tips",
  "interview questions",
  "remote jobs",
  "internship",
  "part time",
  "full time",
  "freelance",
  "career advice",
  "linkedin profile",
];

List<String> responses = [
  "Hello, how can I help you?",
  "Hi there! What can I assist you with?",
  "Are you looking for a job in a specific field?",
  "Let's explore job opportunities together.",
  "Make sure your resume is updated and tailored for each job.",
  "Highlight your key achievements in your CV.",
  "Prepare well before attending any interview.",
  "Research the company you're applying to.",
  "Practice answering common interview questions.",
  "Expected salary depends on your experience and role.",
  "Be honest but realistic when stating your salary expectations.",
  "Many companies now offer remote jobs.",
  "Do you prefer full-time or freelance work?",
  "We can filter jobs based on your location preferences.",
  "What job title are you aiming for?",
  "You can apply through our portal or via company websites.",
  "Make sure your application matches the job description.",
  "A strong career path is built through continuous learning.",
  "Would you like help preparing for your next interview?",
  "Job benefits vary by company, but health insurance and leave days are common.",
  "Working hours usually depend on the role and company policies.",
  "We can guide you step by step through your job application process.",
  "Would you like to know the top companies hiring now?",
  "Remote work offers flexibility but also requires discipline.",
  "Freelance work can be a great option for flexible schedules.",
  "Full-time jobs often include more benefits than part-time or freelance roles.",
  "Make sure your job application is tailored to each position.",
  "Keep your CV clear and concise with relevant experience.",
  "Common interview questions include 'Tell me about yourself' and 'Why should we hire you?'.",
  "Remote jobs are becoming more popular and offer great flexibility.",
  "Internships are a great way to gain practical experience.",
  "Part-time jobs are ideal for students or those seeking flexible hours.",
  "Full-time jobs provide stability and benefits.",
  "Freelance work allows you to work independently on your own schedule.",
  "Career advice can help you make smart professional decisions.",
  "An optimized LinkedIn profile increases your chances of being noticed by recruiters.",
] ;